# Generated by Django 4.0.2 on 2022-02-16 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoomAllotment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='totalSeats',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='room',
            name='vacantSeats',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='roomallotmentrequest',
            name='approvalStatus',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Declined')], default=1),
        ),
        migrations.AddField(
            model_name='roomallotmentrequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='roomallotmentrequest',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='roomallotmentrequest',
            name='skill',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='roomNo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RoomAllotment.room'),
        ),
    ]
