# Generated by Django 4.0.2 on 2022-02-16 19:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RoomAllotment', '0002_room_totalseats_room_vacantseats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provost',
            fields=[
                ('provostID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('password', models.IntegerField(default=123456)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notifID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2022, 2, 16, 19, 55, 28, 34725, tzinfo=utc))),
                ('title', models.CharField(max_length=200)),
                ('details', models.CharField(blank=True, max_length=200, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomAllotment.student')),
            ],
        ),
    ]
