# Generated by Django 4.0.2 on 2022-02-17 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RoomAllotment', '0004_alter_notification_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomallotmentrequest',
            old_name='skill',
            new_name='other_skill',
        ),
        migrations.AddField(
            model_name='provost',
            name='department',
            field=models.CharField(default='CSE', max_length=100),
        ),
        migrations.AddField(
            model_name='provost',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provost',
            name='end_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='provost',
            name='mobile_no',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='provost',
            name='post',
            field=models.CharField(default='Professor', max_length=100),
        ),
        migrations.AddField(
            model_name='provost',
            name='start_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='roomallotmentrequest',
            name='debate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomallotmentrequest',
            name='sports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='CSE', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.IntegerField(default=3, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_no',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='present_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='term',
            field=models.IntegerField(default=2, max_length=20),
        ),
        migrations.AlterField(
            model_name='provost',
            name='password',
            field=models.CharField(default=123456, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=123456, max_length=100),
        ),
    ]
