# Generated by Django 4.0.2 on 2022-02-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomAllotment', '0005_rename_skill_roomallotmentrequest_other_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provost',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='term',
            field=models.IntegerField(default=2),
        ),
    ]
