# Generated by Django 4.0.2 on 2022-02-19 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoomAllotment', '0006_alter_provost_mobile_no_alter_student_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomallotmentrequest',
            name='other',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roomallotmentrequest',
            name='stdID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RoomAllotment.student'),
        ),
    ]
