# Generated by Django 4.0.2 on 2022-02-19 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoomAllotment', '0007_roomallotmentrequest_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomallotmentrequest',
            name='requestedRoomNo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RoomAllotment.room'),
        ),
    ]
