# Generated by Django 4.0.2 on 2022-02-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomAllotment', '0009_alter_roomallotmentrequest_stdid'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notifURL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
